### ISSUE TITLE
Hoppers not extracting correctly from Mythic Chests

### ISSUE THREAD

**Issue by Noaaan** [Noaaan/MythicMetalsDecorations#15]
Caused by vanilla hopper methods only respecting vanilla chests explicitly. 
Needs a full compatibility layer to function correctly.
Lithium compat must also be checked against this.

**Comment by Noaaan** [comment]
As an update, this is still being worked on. Hoppers work as expected when Lithium is not present, although the Lithium compatibility is being reworked. https://github.com/CaffeineMC/lithium-fabric/issues/444

**Comment by Noaaan** [comment]
To note - this issue is partially fixed. Hoppers properly extract from even double chests now. Only in a Lithium context is there still some weirdness to my custom containers.

**Comment by Noaaan** [comment]
I am going to mark this as fixed for now, as using Lithium 0.11.2 for 1.20.1 this seems to no longer be the case

**Comment by Matthew3303** [comment]
Hi, server me and my buddy are playing on is on 1.20 using Lithium 0.11.2, and the hoppers do not extract items from single or double chests at this moment
