### ISSUE TITLE
Compatibility, Double Inventory in Terminal : Tom's v1.58, Mythic Metals Decorations v0.5.3

### ISSUE THREAD

**Issue by rxay579** [Noaaan/MythicMetalsDecorations#19]
Mythic Metals Decorations double chests cause a visual issue in the Tom's Simple Storage terminal where it shows twice the number of items in the network.
Pulling them from the terminal give you the correct number of items.
Single chests do not cause this glitch.

Reported here as well: https://github.com/tom5454/Toms-Storage/issues/258

Tested on a dedicated server instance separate from the client.

**Comment by Noaaan** [comment]
This should be fixed as of Mythic Metals 0.6.0+
![2024-06-12_09 53 35](https://github.com/Noaaan/MythicMetalsDecorations/assets/4163353/4f8b5631-205c-412c-a322-fb8563a93f7f)
![2024-06-12_09 53 38](https://github.com/Noaaan/MythicMetalsDecorations/assets/4163353/f03310c0-9d9c-4bce-be4d-6d1ded8fc696)
