### ISSUE TITLE
Crash : Ticking block entity , Mythic Metals Decorations 0.5.3, Tom's Simple Storage v1.58, Extended Drawers v1.4.1

### ISSUE THREAD

**Issue by rxay579** [Noaaan/MythicMetalsDecorations#20]
Happens on server and single player.

As reported here w/ logs and minimum test setup:
https://github.com/MattiDragon/ExtendedDrawers/issues/70

and here:
https://github.com/tom5454/Toms-Storage/issues/257

**Comment by Noaaan** [comment]
This crash shouldn't happen anymore, as of Mythic Metals Decorations 0.6.0+ this use of the FAPI Transfer API no longer exists, and can therefore not return null.
Feel free to open a new issue should this still be the case
