### ISSUE TITLE
Metal Chest issue

### ISSUE THREAD

**Issue by christian123555** [Noaaan/MythicMetalsDecorations#4]
The Mythic Metal chest don't seem to drop upon breaking with either a silk touch pickaxe or regular, this was done with netherite, as well the menu that comes up when opening the chest to choose what inventory style to use didn't seem to work me and a friend both chose pages but got scroll bar. Really love the look of the chest and want to use them, the stormyx  is beautiful and was really looking forward to using it as my storage system main chest. Still thanks for an amazing mod and would love to see that fixed.

**Comment by Noaaan** [comment]
This was fixed in 0.2.1, please update to this version.

**Comment by Noaaan** [comment]
When it comes to the GUI being forced to scroll this is intended. If this is not set then the chests break whenever you use the third single screen option. 
This will be fixed in a future update once I find an implementation for it.

**Comment by christian123555** [comment]
ok thank you for a fast response and I understand, i know making storage gui can be a hassle, will update and again thanks for an amazing mod.
