### ISSUE TITLE
Placing hopper under manganese chest causes crash

### ISSUE THREAD

**Issue by ObsessedQZR** [Noaaan/MythicMetalsDecorations#5]
Player placed a hopper underneath a manganese chest and crashed the server. Each time the chunk was loaded again, the server crashed. Ended up digging into the crash report to find the hopper and its coords, deleted it through the console while the player was joining in the error chunk.

Might be a mod conflict, just a hunch though.
Attached crash report below.

[crash-2022-05-28_12.25.31-server.txt](https://github.com/Noaaan/MythicMetals/files/8791164/crash-2022-05-28_12.25.31-server.txt)

**Comment by Noaaan** [comment]
I am not able to re-produce this in single-player. If you could test it on a creative world then I would know for sure that its a pure mod-compat issue.

**Comment by Noaaan** [comment]
From this line in the log I am certain this is an incompatability with Lithium:
`net.minecraft.class_2614.handler$cck000$lithiumExtract(class_2614.java:1722)`
This is probably my fault somewhere. I will have this fixed as soon as possible.

**Comment by ObsessedQZR** [comment]
Thank you very much for working on this issue, the community appreciates it a lot! Seeing a mod that receives support isn't that common, so this means a lot!
