### ISSUE TITLE
Can't open chests from this mod

### ISSUE THREAD

**Issue by StockiesLad** [Noaaan/MythicMetalsDecorations#6]
[latest.log](https://github.com/Noaaan/MythicMetalsDecorations/files/8909232/latest.log)

**Comment by Noaaan** [comment]
I think the Container Lib changed the API calls for 1.4.0, meaning that you will have to downgrade to use 0.2.1.
This will be updated for the next version, thanks for the issue

**Comment by StockiesLad** [comment]
oh ok, thanks for the help.

**Comment by Noaaan** [comment]
Should be fixed as of latest commit, will be released very soon

**Comment by StockiesLad** [comment]
sounds good!
